name: Grading Workflow - Assignment 7

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  grade:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Or your desired version

    - name: Download latest test files
      run: |
        # Create the target directory if it doesn't exist
        mkdir -p .github/tests
        # Download from the correct assignment repository (updated to 5)
        # Download the test script as test_assignment.py
        curl -o .github/tests/test_assignment.py https://raw.githubusercontent.com/UCSF-DataSci/datasci223_assignment7/main/.github/tests/test_assignment.py
        # Download the consolidated requirements file as requirements.txt
        curl -o .github/tests/requirements.txt https://raw.githubusercontent.com/UCSF-DataSci/datasci223_assignment7/main/.github/tests/requirements.txt

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install dependencies from the downloaded requirements file
        pip install -r .github/tests/requirements.txt
        # Install repo requirements if they exist
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Setup Jupyter Kernel
      run: |
        python -m ipykernel install --user --name=python3 --display-name="Python 3"

    - name: Run tests
      run: |
        # Data generation and notebook execution are now handled by pytest fixture
        # Run the correct test script (ensure it matches the downloaded name)
        # Assuming the downloaded test script is named test_assignment.py
        # Run the correct test script (downloaded as test_assignment.py)
        pytest .github/tests/test_assignment.py -v