"""Supplied Assignment 01 output wrapper. Students run but do not edit this file."""

from pathlib import Path
import subprocess
import sys


assignment_dir = Path(__file__).resolve().parent
script_names = ("readiness.py", "measurement_summary.py", "debug_report.py")
fresh_output = []

for script_name in script_names:
    completed = subprocess.run(
        [sys.executable, str(assignment_dir / script_name)],
        cwd=assignment_dir,
        capture_output=True,
        text=True,
    )

    if completed.returncode != 0:
        print(f"Could not create output: {script_name} did not run successfully.")
        if completed.stderr:
            print(completed.stderr.rstrip())
        raise SystemExit(1)

    fresh_output.append(completed.stdout.rstrip())

output_dir = assignment_dir / "output"
output_dir.mkdir(exist_ok=True)
output_path = output_dir / "readiness.txt"
output_path.write_text("\n".join(fresh_output) + "\n", encoding="utf-8")

print("Wrote output/readiness.txt from three fresh script runs.")
