name: Assignment 01 - Setup and Email Processing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Download latest test files from upstream
      run: |
        # Create the target directory if it doesn't exist
        mkdir -p .github/tests

        # Download the latest test files from the upstream repository
        # This ensures students always run against the latest tests
        curl -o .github/tests/test_assignment.py \
          https://raw.githubusercontent.com/UCSF-DataSci/ds217_25f_hw1/main/.github/tests/test_assignment.py || true

        # If download fails, use the local version
        if [ ! -f .github/tests/test_assignment.py ]; then
          echo "Using local test file"
        else
          echo "Updated test file from upstream"
        fi

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        # Install any other requirements if they exist
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run tests
      run: |
        # Run the test suite
        pytest .github/tests/test_assignment.py -v --tb=short
